### PR TITLE
Improve “unknown card layout” error message

### PR DESCRIPTION
**Pull request by fenhl**

### CODE REVIEW

**Comment by taw** [comment]
Did you actually see this error? That would be a gap in tests I guess.

**Comment by fenhl** [comment]
I'm seeing it on my `lore-seeker` branch, so I don't know whether it's caused by real or custom cards.

**Comment by taw** [comment]
Presumably that's the new `aftermath` layout.

**Comment by fenhl** [comment]
nope, it's `normal`

**Comment by taw** [comment]
Oh in this context, yeah. Card with `normal` layout isn't supposed to have more than one name.

So the error message is still not very clear, as `normal` is a known layout, just not in this context (as are a bunch of other single-name layouts). Maybe it should list them all and have separate:

`raise "Cards with layout #{card_data["layout"]} are not supposed to have multiple names"`

kind of error.

**Comment by fenhl** [comment]
That would be an option, but my change was enough for me to find the bug: a custom card has the same name as a split card from Amonkhet.

**Pull request merged**
