### PR TITLE
Deck legality logic

### PR DESCRIPTION
**Pull request by fenhl**
I'm working on code that checks the legality of a given deck in a given format. Not sure what would be a good way to expose this in the frontend, maybe a format dropdown in the deck visualizer.

### CODE REVIEW

**Comment by taw** [comment]
This definitely needs some tests.

Frontend needs some logic, simplest case:

* We only display what it's legal in. We don't display what it's not legal in and why.
* 99+1 card decks just check if they're legal in Commander (plus Brawl, and weird Commander variants), no need to check anything else. I mean, someone could play that as Standard deck, but let's be real.
* For any other decks, current Standard, Modern, Legacy, Pauper, and maybe Vintage and Penny Dreadful.
* I guess you'll want to add custom formats to both lists
* The engine knows about a lot more formats - all block formats (which nobody cares about anymore), historical Standard / Modern / etc., but that would totally confuse people. In theory we have data to say things like "This deck was Modern-legal between A (first printing of X) and B (Splinter Twin ban)". It's probably overkill, but we could include some "more ..." button with such things I guess.
* At least we could if mtgjson v4 didn't decide to basically fake release dates for all promos. I should maybe add indexer workarounds for that.

**Comment by taw** [comment]
Approaching the problem from the other side, [I wrote some specs for what it means for a deck to have valid commander/brawler](https://github.com/taw/magic-search-engine/compare/d6cba928121f1bc3884cf337cf39ba51d5afa880...98e6220) as well as a bunch of helpers.

I'm not sure if `Deck` is the right place for that logic.

I definitely don't love those monster methods on your branch. They can definitely be simplified using existing and new helper methods, and those helpers could get comprehensive tests, so `deck_legality` just does a few calls and reporting.

**Comment by taw** [comment]
So I'm adding new relevant helpers to master.
I pulled that into a small branch which I'm rebasing. I'm not sure if I'll end up simplifying and merging it or writing those final checks from scratch using all the helpers.

**Comment by taw** [comment]
All right, `Format#deck_issues` is now a thing. It has different API than this pull request as it lists all issues not just first.

* I partially refactored `Deck` base class out of `PreconDeck`
* it would take a bit more work to make it support user decks - in particular it doesn't support `UnknownCard` yet, and user decks don't create anything that inherits from `Deck`
* messages are a bit on verbose side
* there can be multiple issues about same card (like it's banned, not a partner, and you have 5 of those), or it just picks more important one (if it's banned, doesn't also report you have too many) - it seems fine, but not super consistent
* none of that is exposed in the UI
* I need to clean up all those helpers every now and then, I keep adding them very liberally, but many end up used just once or never really
* I don't love how this logic is smooshed between so many places including `Deck` and `FormatBrawl` near-duplicating `FormatCommander`

**Comment by fenhl** [comment]
Oops, I accidentally pushed Lore Seeker to this branch.

**Comment by taw** [comment]
Deck legality logic should already be fully implemented on `master` branch, right? (`Format#deck_issues` method)

**Comment by fenhl** [comment]
I didn't realize that that method existed at the time. I've integrated my deck legality logic into it on lore-seeker branch now and it seems to be working fine.

**Pull request closed without merging**
