### PR TITLE
Booster/mom

### PR DESCRIPTION
**Pull request by axxroytovu**
Boosters don't work yet. Can't push until MUL data is complete or packs crash.

### CODE REVIEW

**Comment by taw** [comment]
mtgjson updated, so now MUL has all cards, but `e:mul frame:etched` returns nothing, so I guess metadata isn't complete?

There could be another way to query the relevant cards, or if not, we could report an issue to mtgjson.

**Comment by axxroytovu** [comment]
I already reported the issue to scryfall. 

I can grab the cards by number easily enough, but I'm trying to use intuitive queries wherever possible. I can swap it over for now to make the code compile. In the long term I'd like to change it back to `frame:etched` to be as consistent as possible.

**Comment by taw** [comment]
You can always leave a comment about what the query was meant to be.

**Comment by axxroytovu** [comment]
That's what I did for now. I also created a WIP folder for booster files that still need work. 

Draft booster should be accurate. You can merge to load that into the system and I'll fix the set/collector boosters when I get to them.

**Comment by taw** [comment]
OK, I manually merged mom.yaml and plist.txt changes.

**Comment by taw** [comment]
Is it ready to be merged now?

**Comment by axxroytovu** [comment]
Should be. There's some stuff that needs to be cleaned up after MTGJson updates MUL with proper etched tagging and serialized cards but everything else should be correct.

**Pull request merged**
