### PR TITLE
First draft of YAML sheet documentation

### PR DESCRIPTION
**Pull request by axxroytovu**
Add documentation for creating boosters with YAML.

### CODE REVIEW

**Comment by taw** [comment]
This looks reasonable to me. I could make multipart print sheets more flexible if that surprises people. The system was developed for early Magic sets long before any multipart cards.

**Comment by axxroytovu** [comment]
It's really not that big of a deal once you get used to it. It just took me a minute to figure out why Brazen Borrower wasn't working but now I'm just used to it. 

Are there any sections I'm missing or need more detail?

**Comment by taw** [comment]
I think the missing part is how to run it locally and debug it or view the boosters.

Which might be not so obvious, as the image download script is not part of the repo, and Rails pack interface is very image-centric.

**Comment by taw** [comment]
> *If you are adding a new booster or modifying a set code* you will need to execute

> `ruby ./indexer/bin/indexer`

This shouldn't be needed anymore. There are some leftover things it affects like `is:booster` and `st:booster` queries, which I still need to move to the new system, but other than that you shouldn't need reindexing.

**Comment by axxroytovu** [comment]
I tested it and you are correct. I was still reindexing every time I added a new booster so this is very convenient!

**Comment by taw** [comment]
Actually I forgot one case, changing print sheets still requires reindexing.

**Comment by axxroytovu** [comment]
Yeah I kept that bit and removed the reference to adding boosters. 👍

**Comment by taw** [comment]
I moved style section to the end, as it's not really what new reader needs to know first.

Also marked blocks with `yaml` tag so github knows how to highlight it.

**Pull request merged**
