### PR TITLE
Most of the needed changes for Unfinity draft boosters

### PR DESCRIPTION
**Pull request by axxroytovu**
Unfinity boosters did not correctly separate attractions or include shocklands as valid pulls.

### CODE REVIEW

**Comment by axxroytovu** [comment]
This should resolve https://github.com/taw/magic-sealed-data/issues/25

Source: https://magic.wizards.com/en/news/feature/almost-everything-know-about-unfinity-boosters-2022-09-20

**Comment by taw** [comment]
I'm very happy to merge this and other pack yamls, but I'm still finishing the code, and it's easier for me to do this after it's all done. It shouldn't take longer than another week.

**Comment by taw** [comment]
I manually cherry picked patch_exclude_from_boosters.rb part as it doesn't conflict with anything.

**Comment by taw** [comment]
Manually merged contents of unf.yaml. Thanks.

**Comment by axxroytovu** [comment]
No problem. Just trying to find ways to help out while you work on the core code.

**Comment by taw** [comment]
The core code is fine. If you want to do PR, it's probably best to not include `index/*.json` files as they'll probably conflict, and I can easily regenerate them anyway.

**Pull request closed without merging**
