### PR TITLE
MB1: Rename draft booster to retail booster

### PR DESCRIPTION
**Pull request by kodawah**
cc @axxroytovu

### CODE REVIEW

**Comment by axxroytovu** [comment]
Why though? The `retail` tag doesn't add anything and it removes the information that it's a draftable booster.

**Comment by kodawah** [comment]
"retail" is the name of the booster expected in mtg-sealed-content, but every one of mb1 is draftable, it would align with other boosters are tagged (convention-2021 and convention)

**Comment by taw** [comment]
I think "-draft" for the most common kind of draft booster for the set is fine. Convention boosters were just some special extra things, right?

Also right now I have some aliasing logic, where X-draft / X-play / X-mtgo can be aliased as just X ([example](https://mtg.wtf/card?q=booster%3Amb1)). That's quite convenient if you don't remember which sets had which kind as default. This rename would need updating that logic for mb1. Now this quite hacky, but it's nice to have.

**Comment by kodawah** [comment]
im fine renaming the booster type on the other repo, whichever works

**Comment by axxroytovu** [comment]
Fixed in https://github.com/mtgjson/mtg-sealed-content/pull/163

**Pull request closed without merging**
