### PR TITLE
SLC: Add booster definition

### PR DESCRIPTION
**Pull request by kodawah**
as suggested by @axxroytovu 

not sure if magic-preconstructed-deck/SLC.txt needs to be dropped now

### CODE REVIEW

**Comment by taw** [comment]
So you're saying it's a box of 31 cards, each of them has independent 30% chance of being foil? Who tf came up with this idea.

Anyway, I don't think I can merge this. It's technically 2147483648 combinations, in current export format it would crash both my system and mtgjson.

**Comment by kodawah** [comment]
> So you're saying it's a box of 31 cards, each of them has independent 30% chance of being foil? 

correct, except only the first 30 as the last one is the bonus card which is always foil
and there is no correlation between each slot, each kit can contain from 0 to 30 foils, with an average between 8 to 14

> Who tf came up with this idea.

wotc of course :D 
there were many complaints at the time

> Anyway, I don't think I can merge this. It's technically 2147483648 combinations, in current export format it would crash both my system and mtgjson.

do you have any suggestions on how to represent this then? 🤔

**Comment by taw** [comment]
> do you have any suggestions on how to represent this then? 🤔

For this specific case we'd need to restructure data export to allow mixed foil and nonfoil cards on the same sheet. Then we just have 1 booster variant - 31 sheets with 2 cards each.

**Comment by kodawah** [comment]
closing this for now, it would ddos mtgjson or break the output export

**Pull request closed without merging**
