### PR TITLE
Alternate pack building method

### PR DESCRIPTION
**Pull request by axxroytovu**
This method should save a significant amount of space and is back compatible with all the boosters that used the old `pack` notation. 

Note: I don't have the ability to build the pack_factory so this is currently untested.

### CODE REVIEW

**Comment by taw** [comment]
Would it work with something like old style foils (https://mtg.wtf/pack/7ed ?)

Also would it work with something where it's 2 slots alternative, like BBD? This is less important as there's only a few sets like that https://mtg.wtf/pack/bbd

**Comment by axxroytovu** [comment]
It should, as I said I haven't been able to test it.

Old style foils would look like (I don't know the rates):

```
pack:
  basic_slot:
    count: 1
    sheets:
      basic: rate
      foil_basic: rate
  common: 9
  foil_common_slot:
    count: 1
    sheets:
      foil_common: rate
      common: rate
  uncommon: 2
  foil_uncommon_slot:
    count: 1
    sheets:
      foil_uncommon: rate
      uncommon: rate
...
```

Battlebond doesn't quite work because the partners are linked, not sure how to deal with that.

**Comment by taw** [comment]
To test it locally that it works correctly:

```
YAML_PACKS=1 rescue ./bin/export_sealed_data /path/to/magic-sealed-data
```

It should at least not crash.

And check that `git diff` is clean in `/path/to/magic-sealed-data`. Unfortunately it's possible that jsons might be different for trivial reasons like key order. I think the exporter doesn't normalize enough.

Alternatively run `rake rails` and open `http://localhost:3000/pack/one` and `http://localhost:3000/pack/one-yaml` and see if they look the same.

**Comment by taw** [comment]
Not supporting BBD isn't a huge deal, we might just have to list every possibility for it.

**Comment by taw** [comment]
I renamed con.yaml to con_.yaml and adjusted all related code so at least that problem should go away.

**Comment by taw** [comment]
I don't think this branch would support something like https://github.com/taw/magic-search-engine/blob/master/data/boosters/jou.yaml 

Most pack variants will be just foil/common in one slot (or in 3-4 slots for old style foils), but there's quite a dew weird boosters which unfortunately need a specific list.

**Comment by taw** [comment]
I took inspiration from this branch, but ended up with this syntax, as it covers all cases like BBD. Here's 7ED:

```
# I couldn't find information about foils in core sets, so I'm somewhat guessing here
# Treating all of these as independent, totals look hilariously high
pack:
  basic_maybe_foil:
  - basic: 1
    chance: 99 # 100 - 1
  - foil_basic: 1
    chance: 1
  rare_maybe_foil:
  - rare: 1
    chance: 99 # 100 - 1
  - foil_rare: 1
    chance: 1
  uncommon_maybe_foil:
  - uncommon: 3
    chance: 97 # 100 - 3
  - uncommon: 2
    foil_uncommon: 1
    chance: 3
  common_maybe_foil:
  - common: 10
    chance: 90 # 100 - 10
  - common: 9
    foil_common: 1
    chance: 10
```

**Comment by axxroytovu** [comment]
Awesome, glad we found a solution

**Pull request closed without merging**
