### PR TITLE
Updates June 14

### PR DESCRIPTION
**Pull request by axxroytovu**
LTR complete
Some prerelease boosters

### CODE REVIEW

**Comment by taw** [comment]
ltr-collector crashes so I had to disable it.

I'll try to reenable once mtgjson has full spoiler.

**Comment by axxroytovu** [comment]
Strange. I checked it against the current build and it was compiling correctly. Do you have the error message?

**Comment by taw** [comment]
If I enable it and rebuild the index, I then get:

```
$  ./bin/human_export_sealed_data tmp/sealed
/Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:8:in `raise_sheet_error': Error building ltr/extended_core_rare_mythic: No subsheets present (RuntimeError)
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:15:in `build_sheet_from_subsheets'
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:78:in `build_sheet'
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:97:in `build_top_level_sheet'
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:122:in `block in for'
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:121:in `each'
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:121:in `map'
	from /Users/taw/github/magic-search-engine/search-engine/lib/pack_factory.rb:121:in `for'
	from /Users/taw/github/magic-search-engine/search-engine/lib/card_database.rb:127:in `block in supported_booster_types'
	from /Users/taw/github/magic-search-engine/search-engine/lib/card_database.rb:125:in `each_key'
	from /Users/taw/github/magic-search-engine/search-engine/lib/card_database.rb:125:in `supported_booster_types'
	from ./bin/human_export_sealed_data:81:in `call'
	from ./bin/human_export_sealed_data:93:in `<main>'
```

**Comment by axxroytovu** [comment]
Ok. It looks like https://mtg.wtf/card?q=e%3Altr+frame%3Aextendedart+-is%3Afoilonly is returning nothing, but https://scryfall.com/search?q=e%3Altr+frame%3Aextendedart is showing the correct cards. Once that data flows down into MTGJson (hopefully in today's build) then we should be good.

**Comment by taw** [comment]
Reenabled https://mtg.wtf/pack/ltr-collector
Everything builds now

**Pull request merged**
