### PR TITLE
Add a "code" to the deck exporter for easier reference.

### PR DESCRIPTION
**Pull request by axxroytovu**
This tool makes it easier to programmatically refer to a specific deck by code.

Deck codes are in three parts:
`{set code}-{category}-{individual_id}`

The individual ID is the first five non-punctuation letters of the deck's name, followed by incrementing numbers if the deck id already exists.

### CODE REVIEW

**Comment by taw** [comment]
Are these codes used anywhere, or is it just for you?

**Comment by taw** [comment]
By the way, I'm not opposed to adding something like that, if you think it will have some wider use, or if it will make a big difference to you.

**Comment by taw** [comment]
Another by the way, in the search engine there's a way to refer to a specific deck.

If it's unambiguous, [you can use name](https://mtg.wtf/card?q=deck%3A%22Chandra%22), but if there are multiple decks with same name, you can use [deck:"<set>/<name>"](https://mtg.wtf/card?q=deck%3A%22e01%2FChandra%22). So far this system worked for me and I'm not sure the proposed code system would be easier to use.

**Comment by axxroytovu** [comment]
Sorry, this was closed on accident while doing other things.

I added this because I'm trying to unify how my code refers to decks, packs, and sealed products. I don't think anyone else is using this, but I wanted something that was more unique than a name and more human readable than a uuid. It might be useful in the future, so I figured I'd pull this over if you wanted to include it. If you don't want it then no harm done.

**Pull request closed without merging**
