### PR TITLE
Bloomburrow boosters

### PR DESCRIPTION
**Pull request by axxroytovu**

### CODE REVIEW

**Comment by taw** [comment]
```
Sheet blb-play/common is too small to be balanced with only 6 cards
Sheet blb-play/common is too small to be balanced with only 6 cards
```

**Comment by taw** [comment]
I changed common to 

```
common:
    query: "r:c"
```

I think that's what they're going to be going forward.

**Comment by axxroytovu** [comment]
Does this mean that commons are not color balanced at all, or that there is some other balancing scheme?

**Comment by taw** [comment]
Looking at [documentation for play boosters](https://www.lethe.xyz/mtg/collation/mkm.html), it looks like they are only approximately color-balanced, so you can open a pack with no common of certain color, but it's not totally random, and most boosters will be either balanced or nearly so.

Our algorithm that approximates how draft boosters with 10-ish commons worked won't really work here, since there's no mathematical way to guarantee balance, and real packs don't do that either. The algorithm was just a rough approximation anyway.

I think we'll just need to turn off color balancing flag going forward.

We could implement some much more complex scheme given information from The Collation Project, but I'm really not looking forward to it.

**Pull request merged**
