### PR TITLE
Duskmourn & more

### PR DESCRIPTION
**Pull request by axxroytovu**

### CODE REVIEW

**Comment by axxroytovu** [comment]
Named queries helped a lot. The `two_instances` named query is still a mess but it's much better contained this time.

**Comment by axxroytovu** [comment]
These are incorrect but would be fixed by setting the base set size to 286 instead of 301. The "Lurking Evil" cards are considered base set and it's messing with the queries.

**Comment by axxroytovu** [comment]
Also the commander cards aren't showing as having valid non-foil versions but I asked scryfall to fix that.

**Comment by taw** [comment]
They stopped printing base set sizes on cards?

I already have so many base set size overrides, I'm not even sure if they're correct, at some point either me or mtgjson should sort it out, but it was super low priority:

```
Patching base set size for jmp from 495 to 78
Patching base set size for tsr from 289 to 410
Patching base set size for dbl from 633 to 534
Patching base set size for 2x2 from 577 to 331
Patching base set size for brr from 189 to 126
Patching base set size for bro from 292 to 287
Patching base set size for ltr from 289 to 281
```

**Comment by axxroytovu** [comment]
Yeah that's how I tested to make sure that 286 was the correct set size. I can load that change if you are ok having it tied into this PR.

**Comment by taw** [comment]
Yeah, just change the base size in the PR if one in mtgjson is wrong.

At some point we should go through the override list and either fill mtgjson bugs, or stop overriding them if these are wrong.

**Pull request merged**
