### PR TITLE
March of the Machine: Aftermath boosters

### PR DESCRIPTION
**Pull request by axxroytovu**
Leaving this as draft until MAT cards are put into the json. Right now everything crashes when trying to compile.

### CODE REVIEW

**Comment by taw** [comment]
MAT data is incomplete and has some bugs, but it looks like it's good enough to add.

**Comment by taw** [comment]
MAT imported, but some important things are broken including card numbers which cannot decide if they're 37 or 0037.

Are the boosters working now? If not, we can try again after mtgjson update or two.

**Comment by taw** [comment]
common's `foil` sheet will not work for a set without commons, as it thinks there's nonzero chance of common foil, so this crashes.

Fortunately WotC tells us the rates here: "Traditional foil card of any rarity. For approximately 1 in 6 boosters, this is a rare or mythic rare."

**Comment by taw** [comment]
I disabled mat-collector for now, but mat looks good enough with foils fixed.

**Comment by taw** [comment]
mat-collector enabled https://mtg.wtf/pack/mat-collector
@axxroytovu Does it look right to you?

**Comment by axxroytovu** [comment]
I messed up line 35, which should be
`    filter: "e:{set} frame:extendedart"`

otherwise looks good

**Pull request merged**
