### PR TITLE
Color balance with booster type any

### PR DESCRIPTION
**Pull request by axxroytovu**
My attempt to resolve https://github.com/taw/magic-search-engine/issues/207

Everything should be working. I don't know how to modify `search-engine/lib/color_balanced_card_sheet.rb` to properly catch errors but I manually checked that the math does work.

### CODE REVIEW

**Comment by taw** [comment]
Yeah, I wanted to do something like that. I'll need to verify math and run generation.

You can do `search-engine/bin/open_packs 1000xcode` to do empirical results as well.

**Comment by axxroytovu** [comment]
So it does look like these were because of the new balance code, but it's because balanced/any doesn't like being used as a subsheet. I'll go through and correct those tonight when I'm not on my phone.

**Comment by axxroytovu** [comment]
Fixed here https://github.com/taw/magic-search-engine/pull/228

**Comment by taw** [comment]
It should all be working now

**Pull request merged**
