### PR TITLE
Smz/one boosters

### PR DESCRIPTION
**Pull request by axxroytovu**
Update for ONE boosters

### CODE REVIEW

**Comment by axxroytovu** [comment]
Still to do:

- [ ] Implement showcase balancing for cards with multiple showcase treatments
- [ ] Fix implementation in SLX sheet that is preventing it from being read. PLIST works perfectly

**Comment by taw** [comment]
Some notes:

* I see that `promo:`, `frame:` and `number:` range queries can cover most of usecases. That's really good.
* `indexer/lib/patches/patch_has_boosters.rb` changes are fine. Honestly I'll probably replace the whole file with a bunch of `Pathname#exist?` checks so it doesn't need any specific lists of sets.
* if you completely disable `is:booster` system and replace it with default `number<=set`, then it will require updating a lot of booster definitions, or it will break things. Merging this would cause massive regressions everywhere, or a lot of extra annotations in a lot of sets. [There's a lot of other things it filters out](https://mtg.wtf/card?q=e%3A7ed+-is%3Abooster). Originally I was doing `number<=set` (that's why it's still there in the code), but eventually I found out it's not viable.
* for a temporary workaround some kind of `boostercheck: false` to disable `is:booster` checks in nondraft boosters might be better, as it would affect only a few files. This unfortunately means `is:booster` will be a bit wrong, but we can live with it.
* at least foil filter should stay as is; if it ever needs an override, that's a bug in mtgjson
* thinking about long term system, maybe every booster.yaml should have `filter` top level key, defaulting to `filter: number<=set`. And any current exceptions to `is:booster` would go there. So for example [7ED](https://mtg.wtf/card?q=e%3A7ed+-is%3Abooster) could be `filter: number<=set -number:/s/`. The main advantage of this system is that Arena boosters, draft boosters, and non-draft boosters for the same set could have different filters, something not really possible now at all.
* then some kind of integration test could validate that every card that passes the filter is actually in the booster
* and then `is:booster` can be calculated from being in any kind of booster instead of being defined ahead of time

**Comment by axxroytovu** [comment]
I reverted the `is:booster` changes, but allowed the yaml to "opt-out" of `in:booster` by using the same `baseset` syntax I had before. Is that a good compromise?

**Comment by taw** [comment]
I rewrote `PatchHasBoosters` so it just looks which yaml files exists, and doesn't need any explicit lists.
The only things it would need is list of sets that don't have boosters but are included in other sets' boosters, and any with unusual types (SIR and ALA only so far).

I included predefined types default, arena, set, and collector.

It will no longer need patching just because a set got another booster.

Eventually the whole file will go, and files like `ala-premium.yaml` will know their own names, but at least it will no longer get in the way.

**Comment by taw** [comment]
As its name already implied, `rawquery:` is no longer filtered by `is:booster`. I had to add `is:booster` to quite a few of them like all the borrowed basics, BRR etc., but everything builds exactly as before.

Eventually I'd like to add custom `filter:` to each yaml file (default `e:{set} number<=set`) instead of relying on patch file, but this should be fine for now.

I think this should unblock you completely, and now you should be able to PR just the yaml files without code changes.

**Comment by taw** [comment]
Actually I don't really understand `balance_query`. What is it doing?

**Comment by axxroytovu** [comment]
`balance_query` correctly balances cards that have multiple showcase treatments. For ONE:

- Archfiend of the Dross has 1 showcase treatment, so ONE-82 appears 2/3 of the time, and ONE-304 appears 1/3 of the time.
- Jace, the Perfected Mind has 2 showcase treatments, so ONE-57 appears 2/3 of the time, ONE-325 appears 1/6 of the time, and ONE-336 appears 1/6 of the time.
- Elesh Norn has 4 showcase treatments*, so ONE-10 appears 2/3 of the time, and ONE-298, ONE-414, ONE-415, and ONE-416 each appear 1/12 of the time

*note: I still need to confirm whether ONE-416 appears here or as part of the separate praetor sheet but that's a different problem.

**Comment by taw** [comment]
That's awkward, as I really don't want special complicated `balance_query` code in pack factory, and I'd much prefer if we found another solution, but I don't have any great ideas, so we might end up doing that.

Hopefully that's the only issue left.

**Comment by axxroytovu** [comment]
I can do it manually in the yaml with something like this:

```
any:
- rawquery: "e:one ++ r:m promo:boosterfun -is:foilonly -frame:extendedart Elesh Norn, Mother of Machines"
  rate: 1
- rawquery: "e:one ++ r:m promo:boosterfun -is:foilonly -frame:extendedart t:planeswalker"
  rate: 2
- rawquery: "e:one ++ r:m promo:boosterfun -is:foilonly -frame:extendedart -t:planeswalker -(Elesh Norn, Mother of Machines)"
  rate: 4
```

Luckily this set limits it to just the planeswalkers and Norn, but it might require a bigger `(name or name or name)` type search for other sets.

**Comment by taw** [comment]
Yeah, let's try it manually at first, we can improve the code with extra queries later.

**Comment by axxroytovu** [comment]
Ok, that should be a fully manual implementation.

I did make a few fixes to correctly load the Universes Within cards.

**Comment by taw** [comment]
OK, let's merge it, I'll deploy it once all the updates finish.

**Comment by taw** [comment]
All deployed to https://mtg.wtf/pack
You can check if everything is as expected there.

**Comment by axxroytovu** [comment]
Everything looks good, I see one or two things I need to fix but those are my mistake not a programming mistake.

**Pull request merged**
